-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHKQ48iGYSLjTEaMG
NFf6o4R+nGGvybUufEcGrfmmX2WgCgYIKoZIzj0DAQehRANCAASBfrd+dGqfAAD5
O1FQglJhoTxsBqPsWvg6O3LmtAX8DZ8DJCblimmXQWbc4De2u6WlCgd+dL1/snsQ
p7dKjjlE
-----END PRIVATE KEY-----