import { Routes } from '@angular/router';
import { AuthGuard } from './guards/auth.guard';
import { MembershipGuard } from './guards/membership.guard';

export const routes: Routes = [
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: 'login', loadComponent: () => import('./login/login.page').then(m => m.LoginPage) },
  { path: 'home', loadComponent: () => import('./home/home.page').then(m => m.HomePage), canActivate: [AuthGuard] },
  { path: 'registration', loadComponent: () => import('./registration/registration.page').then(m => m.RegistrationPage) },
  { path: 'forgot-password', loadComponent: () => import('./forgot-password/forgot-password.page').then(m => m.ForgotPasswordPage) },
  { path: 'manageAccount', loadComponent: () => import('./manage-account/manage-account.page').then(m => m.ManageAccountPage), canActivate: [AuthGuard]  },
  { path: 'brt', loadComponent: () => import('./brt/brt.page').then(m => m.BRTPage), canActivate: [AuthGuard] },
  { path: 'program', loadComponent: () => import('./program/program.page').then(m => m.ProgramPage), canActivate: [AuthGuard] },
  { path: 'program2', loadComponent: () => import('./program2/program2.page').then(m => m.Program2Page), canActivate: [AuthGuard] },
  { path: 'bb', loadComponent: () => import('./bb/bb.page').then(m => m.BBPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'set', loadComponent: () => import('./set/set.page').then(m => m.SetPage), canActivate: [AuthGuard] },
  { path: 'yogic', loadComponent: () => import('./yogic/yogic.page').then(m => m.YogicPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'bre', loadComponent: () => import('./bre/bre.page').then(m => m.BREPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'brw', loadComponent: () => import('./brw/brw.page').then(m => m.BRWPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'ct', loadComponent: () => import('./ct/ct.page').then(m => m.CTPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'hat', loadComponent: () => import('./hat/hat.page').then(m => m.HATPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'hatc', loadComponent: () => import('./hatc/hatc.page').then(m => m.HATCPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'ahat', loadComponent: () => import('./ahat/ahat.page').then(m => m.AHATPage), canActivate: [MembershipGuard, AuthGuard]},
  { path: 'lungs', loadComponent: () => import('./lungs/lungs.page').then(m => m.LungsPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'wh', loadComponent: () => import('./wh/wh.page').then(m => m.WHPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'setwh', loadComponent: () => import('./setwh/setwh.page').then(m => m.SETWHPage), canActivate: [AuthGuard] },
  { path: 'setkb', loadComponent: () => import('./setkb/setkb.page').then(m => m.SETKBPage), canActivate: [AuthGuard] },
  { path: 'bh', loadComponent: () => import('./bh/bh.page').then(m => m.BHPage), canActivate: [AuthGuard] },
  { path: 'ap', loadComponent: () => import('./ap/ap.page').then(m => m.APPage), canActivate: [AuthGuard] },
  { path: 'kb', loadComponent: () => import('./kb/kb.page').then(m => m.KBPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'prana', loadComponent: () => import('./prana/prana.page').then(m => m.PranaPage), canActivate: [AuthGuard] },
  { path: 'ub', loadComponent: () => import('./ub/ub.page').then(m => m.UBPage), canActivate: [AuthGuard] },
  { path: 'box', loadComponent: () => import('./box/box.page').then(m => m.BOXPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'nb', loadComponent: () => import('./nb/nb.page').then(m => m.NBPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'cb', loadComponent: () => import('./cb/cb.page').then(m => m.CBPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'rb', loadComponent: () => import('./rb/rb.page').then(m => m.RBPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'profile', loadComponent: () => import('./profile/profile.page').then(m => m.ProfilePage), canActivate: [AuthGuard] },
  { path: 'bpr', loadComponent: () => import('./bpr/bpr.page').then(m => m.BPRPage), canActivate: [MembershipGuard, AuthGuard] },
  { path: 'brtresults', loadComponent: () => import('./brtresults/brtresults.page').then(m => m.BrtresultsPage), canActivate: [AuthGuard] },
  { path: 'hatresults', loadComponent: () => import('./hatresults/hatresults.page').then(m => m.HatresultsPage), canActivate: [AuthGuard] },
  { path: 'whresults', loadComponent: () => import('./whresults/whresults.page').then(m => m.WHresultsPage), canActivate: [AuthGuard] },
  { path: 'kbresults', loadComponent: () => import('./kbresults/kbresults.page').then(m => m.KBresultsPage), canActivate: [AuthGuard] },
  { path: 'allresults', loadComponent: () => import('./allresults/allresults.page').then(m => m.ALLresultsPage), canActivate: [AuthGuard] },
  { path: 'sources', loadComponent: () => import('./sources/sources.page').then(m => m.SourcesPage), canActivate: [AuthGuard] }
];
